name: Unit Tests

on:
  push:
    branches-ignore: [main]
    paths:
      - 'scripts/**'
      - 'tests/unit/**'
      - 'tests/helpers/**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        shell: pwsh
        working-directory: ahuofe
        run: |
          Invoke-Pester -Path './tests/unit' -Output Detailed -CI
